If int(os.getenv('IBUS_TYPING_BOOSTER_DEBUG_LEVEL')) does not work, always set debug_level to 0
Doint this only when the execption is “ValueError” is not good,
this makes it fail when a “TypeError” instead of a “ValueError” happens:

    debug_level = int(os.getenv('IBUS_TYPING_BOOSTER_DEBUG_LEVEL'))
TypeError: int() argument must be a string or a number, not 'NoneType'

Better set debug_level to 0 for any kind of exception.