Don’t use keyword arguments when instantiating IBus.LookupTable()
On openSUSE Leap-42, ibus-1.5.13-1.2.x86_64, these errors occur:

TypeError: gobject `IBusLookupTable' doesn't support property `cursor_visible'
TypeError: gobject `IBusLookupTable' doesn't support property `page_size'

I am not sure why this does not happen on Fedora but creating the
IBus.LookupTable() instance without using keyword arguments works on
both openSUSE and Fedora.

I understand it better now, Takao Fujiwara told me that this is because
ibus is build with python2 instead of python3 on SuSE.