add empty file layouts/partials/disqus.html to fix hugo error
$ hugo
WARN  deprecated: the ":filename" permalink token was deprecated in Hugo 0.144.0 and will be removed in a future release. Use ":contentbasename" instead.
Start building sites …
hugo v0.147.8+extended linux/amd64 BuildDate=2025-08-15T00:00:00+00:00 VendorInfo=Fedora:0.147.8-3.fc43

Total in 16 ms
Error: error building site: html/template:_partials/disqus.html:2:14: no such template "_internal/disqus.html"
$ find . -iname disqus.html
./themes/cayman-hugo-theme/layouts/partials/disqus.html
$ cat ./themes/cayman-hugo-theme/layouts/partials/disqus.html
{{ if site.Params.DisqusShortname }}
  {{ template "_internal/disqus.html" . }}
{{ end }}