Ensure enum.Flag's obj._value_ is an integer
In Python 3.10 a new check was added that fails when obj._value_ is not integer
but another enum.Flag's member:

    Traceback (most recent call last):
      File "/usr/share/ibus-typing-booster/engine/emoji_picker.py", line 42, in <module>
        import itb_util
      File "/usr/share/ibus-typing-booster/engine/itb_util.py", line 3191, in <module>
        class InputHints(Flag):
      File "/usr/lib64/python3.10/enum.py", line 484, in __new__
        raise exc
      File "/usr/lib64/python3.10/enum.py", line 246, in __set_name__
        and _is_single_bit(value)
      File "/usr/lib64/python3.10/enum.py", line 73, in _is_single_bit
        num &= num - 1
    TypeError: unsupported operand type(s) for &=: 'InputHints' and 'NoneType'

This should fix https://bugzilla.redhat.com/show_bug.cgi?id=1970626