Fix error when the hunspell dictionary for an engine is missing
 File "/usr/share/ibus-typing-booster/engine/hunspell_suggest.py", line 148, in words_start
    start_words = [unicode('☹ %(loc)s%(dict_name)s not found.' %{'loc': self.loc, 'dict_name': self.dict_name}, 'utf-8'), unicode('☹ please install hunspell dictionary!', 'utf-8') ]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)