Fix encoding error when changing values with the setup tool
This error happened:

    Traceback (most recent call last):
      File "/usr/share/ibus-typing-booster/engine/hunspell_table.py", line 975, in __config_value_changed_cb
        if self.config_section_normalize(self._config_section) != self.config_section_normalize(section):
      File "/usr/share/ibus-typing-booster/engine/hunspell_table.py", line 972, in config_section_normalize
        string.maketrans(string.ascii_uppercase, string.ascii_lowercase ))
    TypeError: character mapping must return integer, None or unicode

Because:

    $ python
    python
    Python 2.7.3 (default, Aug  9 2012, 17:23:57)
    [GCC 4.7.1 20120720 (Red Hat 4.7.1-5)] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import string
    >>> 'AbC'.translate(string.maketrans(string.ascii_uppercase, string.ascii_lowercase))
    'abc'

OK, this works. But:

    >>> u'AbC'.translate(string.maketrans(string.ascii_uppercase, string.ascii_lowercase))
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    TypeError: character mapping must return integer, None or unicode

Can be fixed like this to work both with u'AbC' and 'Abc':

    >>> u'AbC'.translate(string.maketrans(string.ascii_uppercase, string.ascii_lowercase).decode('ISO-8859-1'))
    u'abc'
    >>> 'AbC'.translate(string.maketrans(string.ascii_uppercase, string.ascii_lowercase).decode('ISO-8859-1'))
    u'abc'
    >>>